package corbaConversion;


/**
* corbaConversion/IConversionRemote.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* lundi 4 décembre 2023 22 h 56 WAT
*/

public interface IConversionRemote extends IConversionRemoteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IConversionRemote
